# Data
path: E:\University\Semester 6\Grad\CHICK_t\CHICK_t\April\pose\pose-detection-keypoints-estimation-yolov8-main\pose-detection-keypoints-estimation-yolov8-main\data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [5, 3]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 2, 4, 3]

# Classes
names:
  0: chicken
